-- ============================================================
-- MedAnatomy — Supabase Seed Data
-- Run after 01_schema.sql: 02_seed_data.sql
-- ============================================================

-- ============================================================
-- CRANIAL NERVES
-- ============================================================
INSERT INTO cranial_nerves (number, name, nickname, type, fiber_types, nuclei, ganglion, foramen, origin, termination, functions, branches, mnemonic, embryology, test_method) VALUES

('CN I', 'Olfactory', 'The Smeller', 'Sensory',
 ARRAY['SVA'],
 ARRAY['Olfactory bulb (telencephalon)'],
 NULL,
 'Cribriform plate of ethmoid',
 'Olfactory receptor neurons in nasal mucosa (bipolar neurons)',
 'Olfactory bulb → olfactory tract → primary olfactory cortex (piriform cortex)',
 ARRAY['Special visceral afferent: smell from upper nasal mucosa'],
 NULL,
 'Only CN originating from telencephalon; no thalamic relay',
 'Telencephalon (olfactory placode)',
 'Each nostril separately with common odorants (coffee, vanilla). Anosmia: inability to detect smell.'),

('CN II', 'Optic', 'The Seer', 'Sensory',
 ARRAY['SSA'],
 ARRAY['Lateral geniculate nucleus (thalamus)', 'Superior colliculus'],
 NULL,
 'Optic canal',
 'Retinal ganglion cells (3rd order neuron of visual pathway)',
 'Optic chiasm → optic tract → LGN → optic radiations → primary visual cortex (V1, calcarine sulcus)',
 ARRAY['Special somatic afferent: vision', 'Pupillary light reflex (afferent limb via pretectal nucleus)'],
 ARRAY['Papillomacular bundle','Nasal fibres (cross at chiasm)','Temporal fibres (stay ipsilateral)'],
 'Not a true peripheral nerve — it is a white matter tract (myelinated by oligodendrocytes, not Schwann cells)',
 'Diencephalon',
 'Visual acuity (Snellen chart), visual fields (confrontation), fundoscopy, pupillary light reflex, RAPD (swinging torch test).'),

('CN III', 'Oculomotor', 'The Eye Mover', 'Motor',
 ARRAY['GSE','GVE'],
 ARRAY['Oculomotor nucleus (midbrain tegmentum, level of superior colliculus)', 'Edinger-Westphal nucleus (parasympathetic)'],
 'Ciliary ganglion',
 'Superior orbital fissure',
 'Midbrain interpeduncular fossa',
 'Muscles of the orbit; ciliary ganglion → sphincter pupillae and ciliary muscle',
 ARRAY['GSE: SR, IR, MR, IO, levator palpebrae superioris', 'GVE (para): pupil constriction (miosis), accommodation (lens thickening)'],
 ARRAY['Superior division: SR, levator palpebrae', 'Inferior division: IR, IO, MR + parasympathetic root to ciliary ganglion'],
 'Surgical CN III palsy (PCom aneurysm, herniation): PUPIL DILATED — parasympathetic fibres travel on outer surface. Medical CN III palsy (DM/HTN ischaemia): pupil SPARED — ischaemia affects core first.',
 'Mesencephalon',
 'EOM movements, ptosis assessment, pupil size and reactivity, accommodation reflex.'),

('CN IV', 'Trochlear', 'The Downward Mover', 'Motor',
 ARRAY['GSE'],
 ARRAY['Trochlear nucleus (midbrain, level of inferior colliculus)'],
 NULL,
 'Superior orbital fissure',
 'Only CN to exit from dorsal brainstem; decussates in superior medullary velum',
 'Superior oblique muscle',
 ARRAY['GSE: intorsion (incyclotorsion), depression of adducted eye'],
 NULL,
 'Longest intracranial course, thinnest cranial nerve, only one to exit dorsally and fully decussate',
 'Mesencephalon',
 'Head tilt test (Bielschowsky): head tilt to ipsilateral shoulder increases diplopia in CN IV palsy. Vertical diplopia maximal looking down and in.'),

('CN V', 'Trigeminal', 'The Face Feeler', 'Mixed',
 ARRAY['GSA','SVE'],
 ARRAY['Chief sensory nucleus (pons)','Spinal trigeminal nucleus (medulla/C2–C3)','Mesencephalic nucleus (proprioception)','Motor nucleus of V (pons)'],
 'Trigeminal (Gasserian/semilunar) ganglion',
 'V1: superior orbital fissure | V2: foramen rotundum | V3: foramen ovale',
 'Trigeminal ganglion in Meckel cave (petrous apex)',
 'Face, scalp (anterior to vertex), anterior 2/3 tongue (general sensation), meninges, sinuses, teeth, orbit, nose, hard palate',
 ARRAY['V1 (ophthalmic): forehead, cornea, nose, eye, meninges', 'V2 (maxillary): cheek, upper lip, upper teeth, palate, nasal mucosa', 'V3 (mandibular): lower lip, lower teeth, chin, anterior 2/3 tongue (general), auricle; motor to muscles of mastication, mylohyoid, anterior digastric, tensor tympani, tensor veli palatini'],
 ARRAY['V1: frontal n., lacrimal n., nasociliary n.','V2: zygomatic n., infraorbital n., pterygopalatine branches','V3: auriculotemporal n., inferior alveolar n., lingual n., buccal n., nerve to mylohyoid'],
 'Largest cranial nerve. Motor root is V3 only (from motor nucleus). Corneal reflex: V1 afferent, CN VII efferent.',
 'Branchial arch 1 (mandibular arch) — motor component',
 'Facial sensation in V1/V2/V3 distribution, corneal reflex, jaw jerk (V3 afferent + efferent), muscles of mastication.'),

('CN VI', 'Abducens', 'The Lateral Mover', 'Motor',
 ARRAY['GSE'],
 ARRAY['Abducens nucleus (pons, floor of 4th ventricle)'],
 NULL,
 'Superior orbital fissure',
 'Pons (junction of pons and medulla, paramedian)',
 'Lateral rectus muscle',
 ARRAY['GSE: abduction of the eye (lateral gaze)'],
 NULL,
 'Longest intradural course → false localizing sign in raised ICP. Foville syndrome: ipsilateral gaze palsy + ipsilateral facial nerve palsy (lesion in pons near abducens nucleus). Millard-Gubler: ipsilateral CN VI + VII palsy + contralateral hemiplegia.',
 'Metencephalon (pons)',
 'Ability to abduct eye. Diplopia on lateral gaze to ipsilateral side. Esotropia at rest in CN VI palsy.'),

('CN VII', 'Facial', 'The Face Mover', 'Mixed',
 ARRAY['SVE','GVE','SVA','GSA'],
 ARRAY['Motor nucleus CN VII (pons)','Superior salivatory nucleus (pons)','Nucleus tractus solitarius (taste)','Spinal trigeminal nucleus (somatic sensation)'],
 'Geniculate ganglion (somatic/taste sensory)',
 'Stylomastoid foramen (motor) / Internal acoustic meatus (all divisions enter)',
 'Pons (cerebellopontine angle, with CN VIII)',
 'Muscles of facial expression, scalp; glands (lacrimal, submandibular, sublingual, nasal, palatine); taste anterior 2/3 tongue; skin of auricle',
 ARRAY['SVE: all muscles of facial expression, stapedius, stylohyoid, posterior digastric', 'GVE (para): lacrimal gland (via greater petrosal n. → pterygopalatine ganglion); submandibular + sublingual glands (via chorda tympani → submandibular ganglion)', 'SVA: taste anterior 2/3 tongue via chorda tympani', 'GSA: skin of auricle/EAC (nerve of Wrisberg)'],
 ARRAY['Greater petrosal nerve (at geniculate ganglion) → lacrimal gland', 'Nerve to stapedius (in facial canal)', 'Chorda tympani (joins lingual nerve V3) → taste + submandibular/sublingual glands', 'Extratemporal: temporal, zygomatic, buccal, marginal mandibular, cervical'],
 'UMN facial palsy (stroke): spares forehead (bilateral cortical representation). LMN facial palsy (Bell palsy): entire face involved including forehead. Localization: lesion above chorda tympani junction → taste lost + hyperacusis; at geniculate → + lacrimation affected; below stylomastoid → pure motor.',
 'Branchial arch 2 (hyoid arch)',
 'Facial movement (forehead, eye closure, smile), corneal reflex (efferent), taste anterior 2/3 tongue, Schirmer lacrimation test, stapedial reflex.'),

('CN VIII', 'Vestibulocochlear', 'The Hearing/Balance Nerve', 'Sensory',
 ARRAY['SSA'],
 ARRAY['Cochlear nuclei (dorsal + ventral, pontomedullary junction)', 'Vestibular nuclei (4 nuclei, pons/medulla)'],
 'Spiral ganglion (cochlear) / Scarpa ganglion (vestibular)',
 'Internal acoustic meatus',
 'Organ of Corti (cochlear division), semicircular canals/utricle/saccule (vestibular division)',
 'Brainstem cochlear and vestibular nuclei',
 ARRAY['SSA cochlear: hearing', 'SSA vestibular: linear acceleration (utricle/saccule), angular acceleration (semicircular canals), VOR'],
 ARRAY['Cochlear division', 'Vestibular division (superior + inferior)'],
 'Acoustic neuroma (vestibular schwannoma) at IAM → tinnitus, unilateral SNHL, imbalance. Weber test: sound lateralises to affected ear (conductive) or healthy ear (sensorineural). Rinne test: BC > AC in conductive loss. HINTS exam (Head Impulse, Nystagmus, Test of Skew) differentiates central from peripheral vertigo.',
 'Otic placode',
 'Pure tone audiometry, Weber/Rinne tuning fork tests, HINTS exam for acute vertigo, caloric testing, VNG.'),

('CN IX', 'Glossopharyngeal', 'The Throat Nerve', 'Mixed',
 ARRAY['SVE','GVE','SVA','GVA','GSA'],
 ARRAY['Nucleus ambiguus (motor, SVE)', 'Inferior salivatory nucleus (GVE)', 'Nucleus tractus solitarius (taste + visceral afferent)', 'Spinal trigeminal nucleus (GSA)'],
 'Superior (somatic) and Inferior (petrosal/visceral) ganglia',
 'Jugular foramen',
 'Lateral medulla (postolivary sulcus)',
 'Posterior pharynx, palatine tonsil, posterior 1/3 tongue (taste + sensation), carotid sinus/body, parotid gland, middle ear',
 ARRAY['SVE: stylopharyngeus (only muscle solely innervated by CN IX)', 'GVE (para): parotid gland via lesser petrosal n. → otic ganglion', 'SVA: taste posterior 1/3 tongue', 'GVA: carotid sinus baroreceptors, carotid body chemoreceptors, pharyngeal mucosa', 'GSA: posterior pharynx, auricle, EAC, tympanic membrane (Jacobson nerve)'],
 ARRAY['Tympanic nerve (Jacobson nerve) → lesser petrosal → otic ganglion → auriculotemporal → parotid', 'Carotid sinus nerve', 'Pharyngeal branches'],
 'Gag reflex afferent (CN IX) + efferent (CN X). Carotid sinus syncope (hypersensitivity of baroreceptor). Glossopharyngeal neuralgia: stabbing pain in posterior pharynx/ear triggered by swallowing.',
 'Branchial arch 3',
 'Gag reflex, taste posterior 1/3 tongue, pharyngeal sensation, carotid sinus reflex.'),

('CN X', 'Vagus', 'The Wanderer', 'Mixed',
 ARRAY['SVE','GVE','SVA','GVA','GSA'],
 ARRAY['Nucleus ambiguus (SVE + branchial motor)', 'Dorsal motor nucleus (GVE parasympathetic)', 'Nucleus tractus solitarius (SVA taste + GVA visceral)', 'Spinal trigeminal nucleus (GSA)'],
 'Superior (jugular) and Inferior (nodose) ganglia',
 'Jugular foramen',
 'Lateral medulla (postolivary sulcus, caudal to CN IX)',
 'Pharynx, larynx, thoracic and abdominal viscera to left colic flexure',
 ARRAY['SVE: all intrinsic laryngeal muscles (via RLN) except cricothyroid (superior laryngeal n. external branch); pharyngeal constrictors; soft palate (except tensor veli palatini V3)', 'GVE (para): heart (bradycardia), lungs (bronchoconstriction), gut to left colic flexure (peristalsis, secretions)', 'SVA: taste from epiglottis and valleculae', 'GVA: aortic arch baroreceptors/chemoreceptors, oesophagus, trachea, viscera', 'GSA: auricle, EAC, posterior cranial fossa dura (Arnold nerve)'],
 ARRAY['Pharyngeal branch (with CN IX → pharyngeal plexus)', 'Superior laryngeal nerve → internal branch (sensory) + external branch (cricothyroid)', 'Recurrent laryngeal nerve (all intrinsic laryngeal muscles except cricothyroid)', 'Cardiac branches', 'Pulmonary branches', 'Oesophageal plexus', 'Gastric branches'],
 'RLN palsy: hoarse voice (breathy, bovine cough). Left RLN loops under aortic arch (longer) — more vulnerable to mediastinal/lung pathology, aortic aneurysm. Right RLN loops under right subclavian. Both at risk in thyroid surgery. Uvula deviation: LMN lesion → uvula deviates AWAY from lesion side; UMN → deviation toward lesion. Vagal syncope (vasovagal).',
 'Branchial arches 4 and 6',
 'Voice quality (hoarseness), soft palate elevation (uvula deviates away from LMN lesion), gag reflex (efferent), laryngoscopy for vocal cord movement.'),

('CN XI', 'Accessory', 'The Shoulder Shrugging Nerve', 'Motor',
 ARRAY['SVE'],
 ARRAY['Nucleus ambiguus (cranial root, joins vagus)', 'Anterior horn C1–C5 (spinal root)'],
 NULL,
 'Jugular foramen',
 'Cranial root from nucleus ambiguus → joins vagus (laryngeal muscles); Spinal root from anterior horn C1–C5 → ascends through foramen magnum → exits jugular foramen',
 'Cranial root rejoins vagus for laryngeal muscles; Spinal root → sternocleidomastoid and trapezius',
 ARRAY['Cranial root: contributes to laryngeal muscles via vagus', 'Spinal root: SCM (ipsilateral head rotation) and trapezius (shoulder elevation, scapular retraction)'],
 NULL,
 'Most commonly injured in posterior triangle neck dissections/lymph node biopsy → dropped shoulder (trapezius palsy), winging of scapula (lateral), weakness turning head away from lesion.',
 'Branchial arch 4/6 (cranial root); Spinal cord anterior horn (spinal root)',
 'Shoulder shrug against resistance (trapezius), head turning against resistance (SCM). SCM: turns head to contralateral side.'),

('CN XII', 'Hypoglossal', 'The Tongue Mover', 'Motor',
 ARRAY['GSE'],
 ARRAY['Hypoglossal nucleus (medulla, floor of 4th ventricle)'],
 NULL,
 'Hypoglossal canal (anterior condylar canal)',
 'Medulla (preolivary sulcus)',
 'All intrinsic tongue muscles + extrinsic muscles (genioglossus, hyoglossus, styloglossus). Exception: palatoglossus = CN X',
 ARRAY['GSE: tongue movements — protrusion (genioglossus), retraction, depression, shape changes for speech and swallowing'],
 NULL,
 'LMN (ipsilateral) lesion: tongue deviates TOWARD lesion on protrusion (weak side collapses). UMN (contralateral) lesion: tongue deviates AWAY from lesion. Fasciculations and atrophy = LMN. At risk during carotid endarterectomy (passes near carotid bifurcation).',
 'Occipital myotomes',
 'Tongue protrusion and movement, assess for fasciculations and wasting, dysarthria assessment.');

-- Clinical correlations for CN III
INSERT INTO cn_clinical_correlations (cranial_nerve_id, condition, description, signs)
SELECT id, 'Posterior Communicating Artery Aneurysm', 
  'PCom aneurysm compresses CN III from outside-in. Parasympathetic fibres (pupil constriction) run on outer surface → pupil is dilated (fixed, unreactive) FIRST. This is a surgical emergency.',
  ARRAY['Ptosis (levator palpebrae)','Ophthalmoplegia (down and out position)','Fixed dilated pupil','Diplopia']
FROM cranial_nerves WHERE number = 'CN III';

INSERT INTO cn_clinical_correlations (cranial_nerve_id, condition, description, signs)
SELECT id, 'Medical (Ischaemic) CN III Palsy',
  'Microvascular ischaemia (DM, HTN) affects core fibres first. Parasympathetic pupillomotor fibres are on periphery → pupil is SPARED (reactive). Medical palsy resolves spontaneously in ~3 months.',
  ARRAY['Ptosis','Complete ophthalmoplegia','Pupil SPARED (normal size and reactive)','Pain may occur']
FROM cranial_nerves WHERE number = 'CN III';

INSERT INTO cn_clinical_correlations (cranial_nerve_id, condition, description, signs)
SELECT id, 'Transtentorial (Uncal) Herniation',
  'Uncus of temporal lobe herniates over tentorium cerebelli, compressing ipsilateral CN III → blown pupil is IPSILATERAL to lesion (compression of afferent pupillary pathway).',
  ARRAY['Ipsilateral fixed dilated pupil (earliest sign)','Ipsilateral CN III palsy','Contralateral hemiplegia (CST compression)','Depressed consciousness']
FROM cranial_nerves WHERE number = 'CN III';

-- ============================================================
-- MUSCLES (key selection — expand as needed)
-- ============================================================
INSERT INTO muscles (slug, name, region, origin, insertion, actions, nerve, nerve_roots, blood_supply, clinical_note, special_tests, notes) VALUES

('supraspinatus','Supraspinatus','Rotator Cuff / Shoulder',
 'Supraspinous fossa of scapula (medial 2/3)',
 'Superior facet of greater tubercle of humerus; superior glenohumeral joint capsule',
 ARRAY['Initiates abduction (first 15°)','Stabilizes glenohumeral joint (compresses head of humerus into glenoid)'],
 'Suprascapular nerve','C5–C6',
 'Suprascapular artery',
 'Most commonly torn rotator cuff muscle. Avascular zone ("critical zone") 1 cm from insertion. Impingement under coracoacromial arch. Full thickness tear: pain + weakness initiating abduction; drop arm sign. Partial thickness tears may be asymptomatic.',
 ARRAY['Painful arc test (60°–120°)','Neer impingement sign','Hawkins-Kennedy test','Drop arm test','Jobe empty-can test'],
 'Suprascapular nerve can be entrapped at suprascapular notch (under transverse scapular ligament). Distinguished from infraspinatus: supraspinatus = abduction; infraspinatus = external rotation.'),

('infraspinatus','Infraspinatus','Rotator Cuff / Shoulder',
 'Infraspinous fossa of scapula (medial 2/3)',
 'Middle facet of greater tubercle of humerus',
 ARRAY['External (lateral) rotation of humerus','Stabilizes glenohumeral joint'],
 'Suprascapular nerve','C5–C6',
 'Suprascapular artery',
 'Suprascapular nerve entrapment at spinoglenoid notch selectively affects infraspinatus (spares supraspinatus). Isolated infraspinatus wasting. External rotation lag sign indicates tear.',
 ARRAY['External rotation lag sign','Hornblower sign (teres minor + infraspinatus)'],
 NULL),

('teres-minor','Teres Minor','Rotator Cuff / Shoulder',
 'Upper 2/3 lateral border of scapula (posterior surface)',
 'Inferior facet of greater tubercle of humerus',
 ARRAY['External rotation of humerus','Adduction of humerus','Stabilizes glenohumeral joint'],
 'Axillary nerve','C5–C6',
 'Posterior circumflex humeral artery',
 'Quadrilateral space syndrome: axillary nerve and posterior circumflex humeral artery compressed in quadrilateral space (bounded by: teres minor, teres major, long head triceps, surgical neck humerus). Presents with deltoid + teres minor wasting, posterior shoulder pain.',
 ARRAY['Hornblower sign'],
 NULL),

('subscapularis','Subscapularis','Rotator Cuff / Shoulder',
 'Subscapular fossa (anterior surface of scapula)',
 'Lesser tubercle of humerus; anterior glenohumeral joint capsule',
 ARRAY['Medial (internal) rotation of humerus','Adduction of humerus','Stabilizes glenohumeral joint'],
 'Upper and lower subscapular nerves','C5–C6',
 'Subscapular artery',
 'Largest and strongest rotator cuff muscle. Tear causes external rotation weakness and loss of internal rotation. Lift-off test and bear hug test are specific for subscapularis.',
 ARRAY['Lift-off test (Gerber)','Bear hug test','Belly press test','Napoleon test'],
 'Only rotator cuff muscle originating from anterior scapula. Innervated by subscapular nerves from posterior cord (not suprascapular nerve).'),

('biceps-brachii','Biceps Brachii','Arm (Anterior)',
 'Long head: supraglenoid tubercle + glenoid labrum. Short head: coracoid process (with coracobrachialis)',
 'Radial tuberosity; bicipital aponeurosis (lacertus fibrosus) → deep fascia of forearm',
 ARRAY['Flexion of elbow (primary)','Supination of forearm (most powerful supinator when elbow flexed to 90°)','Weak shoulder flexion'],
 'Musculocutaneous nerve','C5–C6',
 'Brachial artery (muscular branches)',
 'Proximal rupture (long head): "Popeye sign" — muscle belly displaced distally. Distal rupture: muscle belly displaced proximally; hook test (inability to hook examiner''s finger under bicipital aponeurosis). Speed test + Yergason test for bicipital tendinopathy/SLAP lesion.',
 ARRAY['Speed test','Yergason test','Hook test (distal rupture)'],
 'Only muscle that crosses both shoulder and elbow. Supination most effective with elbow at 90°.'),

('triceps-brachii','Triceps Brachii','Arm (Posterior)',
 'Long head: infraglenoid tubercle of scapula. Lateral head: posterior humerus (proximal, above radial groove). Medial head: posterior humerus (distal, below radial groove)',
 'Olecranon process of ulna; fascia of forearm',
 ARRAY['Extension of elbow (primary)','Long head: adduction + extension of shoulder'],
 'Radial nerve','C6–C8 (primarily C7)',
 'Profunda brachii (deep brachial artery)',
 'Saturday night palsy / honeymoon palsy: radial nerve compressed in spiral (radial) groove of humerus → wrist drop (extensor paralysis), loss of finger/thumb extension, sensory loss dorsal hand/first web space. Triceps usually SPARED (branch to triceps given off before spiral groove).',
 ARRAY['Triceps reflex (C7)'],
 'Most powerful elbow extensor. C7 is the primary root (C7 reflex hammer test = triceps reflex).'),

('deltoid','Deltoid','Shoulder',
 'Anterior: lateral clavicle (1/3). Middle: acromion. Posterior: spine of scapula',
 'Deltoid tuberosity of humerus',
 ARRAY['Anterior: flexion, medial rotation, horizontal adduction','Middle: abduction (60°–180° with supraspinatus)','Posterior: extension, lateral rotation, horizontal abduction'],
 'Axillary nerve','C5–C6',
 'Posterior circumflex humeral artery',
 'Axillary nerve injury: most common with anterior shoulder dislocation or proximal humerus fracture (surgical neck). Deltoid weakness (abduction beyond 15°) + patch of sensory loss over regimental badge area (upper outer arm).',
 ARRAY['Regimental badge sensory test'],
 'Middle deltoid + supraspinatus together abduct arm 0–180°. Isolated supraspinatus: 0–15°.'),

('gluteus-medius','Gluteus Medius','Gluteal / Hip',
 'Ilium (outer surface, between anterior and posterior gluteal lines)',
 'Greater trochanter of femur (lateral surface)',
 ARRAY['Abduction of hip (primary)','Medial rotation (anterior fibres)','Stabilization of pelvis during walking (single leg stance)'],
 'Superior gluteal nerve','L4–L5',
 'Superior gluteal artery',
 'Trendelenburg sign and gait: weakness causes contralateral pelvis to drop during single-leg stance (pelvis tilts toward unsupported side). Causes: superior gluteal nerve injury, hip OA, DDH, post hip replacement, polio. Used to assess hip abductor strength in all hip pathology.',
 ARRAY['Trendelenburg test','Hip abductor strength testing'],
 'Superior gluteal nerve exits greater sciatic foramen ABOVE piriformis (along with superior gluteal vessels). Innervates gluteus medius, gluteus minimus, and tensor fascia lata.'),

('piriformis','Piriformis','Gluteal / Hip',
 'Anterior sacrum (S2–S4) and sacrotuberous ligament',
 'Superior aspect of greater trochanter (medial surface)',
 ARRAY['External rotation of hip (when extended)','Abduction of hip (when flexed >60°)','Stabilization of hip joint and sacroiliac joint'],
 'Nerve to piriformis (direct branch of sacral plexus)','S1–S2',
 'Inferior gluteal artery; superior gluteal artery',
 'Sciatic nerve relationship: in 85% passes BELOW piriformis; in 10–15% the common peroneal division passes THROUGH piriformis (anatomical variant). Piriformis syndrome: deep buttock pain radiating down leg, exacerbated by FAIR position (Flexion, Adduction, Internal Rotation). Distinguish from disc herniation: no neurological deficit at rest, worse with prolonged sitting.',
 ARRAY['FAIR test','Pace test','Freiberg sign'],
 NULL),

('iliopsoas','Iliopsoas','Hip Flexors',
 'Iliacus: iliac fossa. Psoas major: T12–L5 vertebral bodies, transverse processes, intervertebral discs',
 'Lesser trochanter of femur',
 ARRAY['Flexion of hip (most powerful)','Lateral rotation of hip','Stabilization of lumbar spine and lumbosacral junction'],
 'Femoral nerve (L2–L4) for iliacus; direct branches of lumbar plexus (L1–L3) for psoas','L1–L4',
 'Iliolumbar artery; lateral femoral circumflex',
 'Psoas abscess: TB or Crohn disease tracks along psoas sheath → present as unexplained hip flexion deformity, lumbar swelling, fever. Thomas test: fixed hip flexion deformity due to tight iliopsoas. Femoral nerve compression in iliopsoas haematoma (anticoagulation). Snapping hip (coxa saltans): iliopsoas tendon snaps over iliopectineal eminence.',
 ARRAY['Thomas test (hip flexion contracture)','Straight leg raise against resistance'],
 'Psoas major also acts as lateral flexor of lumbar spine. Only muscle connecting spine directly to lower limb.'),

('gastrocnemius','Gastrocnemius','Leg (Posterior Superficial)',
 'Medial head: medial femoral condyle. Lateral head: lateral femoral condyle',
 'Calcaneus via Achilles tendon (with soleus)',
 ARRAY['Plantarflexion of ankle (primary)','Flexion of knee','Contributes to knee stability'],
 'Tibial nerve','S1–S2',
 'Sural arteries (branches of popliteal artery)',
 'Achilles tendon rupture (gastrocnemius-soleus complex): Thompson test — positive if squeezing the calf does NOT produce plantarflexion. Palpable gap. Most common at the "watershed zone" 2–6 cm above calcaneal insertion. Tennis leg: acute tear of medial head of gastrocnemius at musculotendinous junction. Silfverskiöld test: tight gastrocnemius (ankle dorsiflexion limited with knee extended, improves with knee flexed = isolated gastrocnemius tightness).',
 ARRAY['Thompson (Simmonds) test','Silfverskiöld test'],
 'Unlike soleus, gastrocnemius crosses the knee — tightness tested with knee extended (Silfverskiöld). Ankle jerk (S1) tests gastrocnemius-soleus complex.'),

('tibialis-anterior','Tibialis Anterior','Leg (Anterior)',
 'Lateral tibia (upper 2/3) and interosseous membrane',
 'Medial cuneiform and base of 1st metatarsal',
 ARRAY['Dorsiflexion of ankle (primary)','Inversion of foot'],
 'Deep peroneal (fibular) nerve','L4–L5',
 'Anterior tibial artery',
 'Foot drop: weakness of all dorsiflexors (L4–L5 root lesion, common peroneal nerve injury). Common peroneal nerve most commonly injured at fibular neck (fractures, prolonged squatting, plaster casts). Anterior compartment syndrome: raised intra-compartmental pressure → pain, tense compartment, pain on passive stretch, paraesthesia dorsal foot. Fasciotomy required.',
 ARRAY['Heel walk test (L4–L5)'],
 'L4 root lesion: isolated tibialis anterior weakness + sensory loss medial lower leg. Common peroneal nerve injury: foot drop + sensory loss dorsum foot/first web space (no inversion weakness = peroneal muscles intact).'),

('diaphragm','Diaphragm','Thorax / Respiration',
 'Xiphoid process (sternal part), lower 6 costal cartilages and ribs (costal part), L1–L3 vertebrae and arcuate ligaments (lumbar part / crura)',
 'Central tendon',
 ARRAY['Primary muscle of inspiration (80% of tidal volume)', 'Increases intrathoracic volume → decreases pressure → air enters lungs', 'Increases intra-abdominal pressure (Valsalva, defecation, parturition)'],
 'Phrenic nerve (C3, C4, C5)','C3–C5',
 'Pericardiophrenic artery (from internal thoracic); musculophrenic artery; inferior phrenic artery',
 'Openings: T8 = IVC + right phrenic nerve; T10 = oesophagus + vagal trunks + left gastric vessels; T12 = aorta + thoracic duct + azygos vein. "I (8) ate (10) eggs (12) at (aorta) twelve". Diaphragmatic hernias: Bochdalek (posterolateral, most common, L>R) — neonatal respiratory distress; Morgagni (anterior, rare). Phrenic nerve palsy (C3–C5 injury, tumour, cardiac surgery) → paradoxical diaphragm movement. Kehr''s sign: left shoulder pain from diaphragmatic irritation (splenic rupture, ectopic pregnancy).',
 ARRAY['Chest X-ray for paradoxical movement','Sniff test under fluoroscopy'],
 'C3,4,5 keeps the diaphragm alive. Bilateral phrenic nerve damage = ventilator dependence. Hiccup = involuntary diaphragmatic spasm.'),

('external-intercostals','External Intercostals','Thorax',
 'Lower border of rib above (posterior to mid-axillary line)',
 'Upper border of rib below',
 ARRAY['Elevation of ribs → increases anterior-posterior and transverse thoracic diameter → inspiration'],
 'Intercostal nerves (anterior rami T1–T11)','T1–T11',
 'Posterior and anterior intercostal arteries',
 'Chest drain insertion: should pass OVER the upper border of the lower rib (to avoid intercostal neurovascular bundle — VAN = Vein, Artery, Nerve — running in subcostal groove of rib above). Safe triangle for chest drain: 4th/5th ICS, anterior to mid-axillary line, lateral to pectoralis major.',
 NULL,
 'VAN mnemonic: Vein (most superior), Artery, Nerve in subcostal groove. Always approach ABOVE the rib to avoid the bundle.'),

('rectus-abdominis','Rectus Abdominis','Abdomen',
 'Pubic crest and pubic symphysis',
 '5th, 6th, 7th costal cartilages; xiphoid process',
 ARRAY['Flexion of trunk', 'Compression of abdominal contents', 'Stabilization of pelvis during walking'],
 'Intercostal nerves T7–T12; subcostal nerve T12','T7–T12',
 'Superior epigastric (from internal thoracic) and inferior epigastric (from external iliac) arteries',
 'Rectus sheath: above arcuate line (mid-point between umbilicus and pubic symphysis) — anterior wall = external oblique aponeurosis + anterior lamina of internal oblique; posterior wall = posterior lamina of internal oblique + transversus abdominis. Below arcuate line: all aponeuroses pass anteriorly → no posterior sheath (only transversalis fascia). Epigastric hernia: protrusion through linea alba above umbilicus. TRAM/DIEP flap: rectus abdominis used in breast reconstruction (based on inferior epigastric vessels for DIEP flap).',
 NULL,
 'Tendinous intersections (3 above umbilicus, 1 at umbilicus level) fuse to anterior rectus sheath, not posterior — explains why rectus can be separated from posterior sheath but adherent anteriorly.'),

('sternocleidomastoid','Sternocleidomastoid','Neck',
 'Sternal head: manubrium sterni. Clavicular head: medial 1/3 of clavicle',
 'Mastoid process and lateral superior nuchal line',
 ARRAY['Unilateral: rotation of head to CONTRALATERAL side, lateral flexion to IPSILATERAL side', 'Bilateral: flexion of head and neck, assists in forced inspiration (elevates sternum)'],
 'Accessory nerve (CN XI) motor; C2–C3 proprioception','C2–C3 (sensory) + CN XI (motor)',
 'Occipital artery; superior thyroid artery',
 'CN XI most commonly injured during posterior triangle neck surgery (lymph node biopsy, radical neck dissection) → weakness turning head to contralateral side + shoulder drop (trapezius paralysis). Torticollis (wry neck): contracture of SCM → ipsilateral head tilt, contralateral rotation. Sternocleidomastoid divides neck into anterior and posterior triangles.',
 ARRAY['Head turning against resistance','Chin-to-shoulder test'],
 NULL);

-- ============================================================
-- MNEMONICS
-- ============================================================
INSERT INTO mnemonics (slug, mnemonic, full_form, meaning, category) VALUES

('cn-names','On Old Olympus Towering Tops A Finn And German Viewed Some Hops',
 'Olfactory, Optic, Oculomotor, Trochlear, Trigeminal, Abducens, Facial, Auditory(Vestib), Glossopharyngeal, Vagus, (Spinal) Accessory, Hypoglossal',
 'Names of CN I through CN XII in order','Cranial Nerves'),

('cn-types','Some Say Marry Money But My Brother Says Big Brains Matter More',
 'S=Sensory, M=Motor, B=Both (Mixed)',
 'CN I=S, II=S, III=M, IV=M, V=B, VI=M, VII=B, VIII=S, IX=B, X=B, XI=M, XII=M','Cranial Nerves'),

('cn-foramina-v','Standing Room Only',
 'Superior orbital fissure, Foramen Rotundum, Foramen Ovale',
 'Exit foramina for CN V1, V2, V3','Cranial Nerves'),

('sits-rotator-cuff','SITS',
 'Supraspinatus, Infraspinatus, Teres Minor, Subscapularis',
 'The four rotator cuff muscles','Shoulder / Rotator Cuff'),

('carpal-bones','Some Lovers Try Positions That They Cannot Handle',
 'Scaphoid, Lunate, Triquetrum, Pisiform, Trapezium, Trapezoid, Capitate, Hamate',
 'Carpal bones in order from radial to ulnar, proximal then distal row','Wrist / Carpal Bones'),

('cubital-fossa','My Bottoms Really Really Tasty',
 'Medial to lateral: Median nerve, Brachial artery, Biceps tendon, Radial nerve, nerve to brachioradialis (posterior interosseous nerve)',
 'Contents of the cubital fossa from medial to lateral','Elbow'),

('femoral-triangle-navel','NAVEL',
 'Nerve, Artery, Vein, Empty space, Lymphatics',
 'Contents of femoral triangle from lateral to medial (N=femoral nerve, A=femoral artery, V=femoral vein, E=empty space, L=lymphatics). Femoral canal = most medial compartment.','Hip / Femoral Triangle'),

('brachial-plexus-roots','Real Truckers Drink Cold Beer',
 'Roots, Trunks, Divisions, Cords, Branches',
 'Organisation of the brachial plexus (RTDCB)','Brachial Plexus'),

('lumbar-plexus','I Get Laid On Fridays',
 'Iliohypogastric, Genitofemoral, Lateral femoral cutaneous, Obturator, Femoral',
 'Branches of the lumbar plexus from T12/L1 to L4','Lower Limb / Lumbar Plexus'),

('diaphragm-openings','I 8 10 Eggs At 12',
 'IVC at T8, Oesophagus at T10, Aorta at T12',
 'Diaphragm openings by vertebral level: I=IVC, 8=T8; 10=Oesophagus at T10; Eggs=Aorta, At=At, 12=T12','Thorax / Diaphragm'),

('inguinal-hernia-indirect-deep','IPSIL',
 'Indirect, Passes through deep ring, Same side (ipsilateral), Into scrotum possible, Lateral to inferior epigastric',
 'Indirect inguinal hernia: passes through deep inguinal ring (lateral to inferior epigastric vessels), travels through inguinal canal, may enter scrotum; congenital (patent processus vaginalis).','Abdomen / Hernia'),

('scalp-layers','SCALP',
 'Skin, Connective tissue (dense), Aponeurosis (epicranial/galea aponeurotica), Loose areolar tissue (danger zone — infection spreads here), Pericranium (periosteum)',
 'Five layers of the scalp from superficial to deep. Danger zone = loose areolar layer (emissary veins connect to intracranial sinuses — infection can spread to cavernous sinus).','Head and Neck'),

('loaf-median-nerve','LOAF',
 'Lumbricals 1 and 2, Opponens pollicis, Abductor pollicis brevis, Flexor pollicis brevis (superficial head)',
 'Intrinsic hand muscles innervated by the median nerve (thenar muscles + lateral two lumbricals)','Upper Limb / Hand'),

('ulnar-nerve-hand','All For One',
 'Adductor pollicis, Flexor pollicis brevis (deep head), all other intrinsic hand muscles (interossei, medial 2 lumbricals, hypothenar group)',
 'Ulnar nerve innervates all intrinsic hand muscles EXCEPT LOAF (median nerve)','Upper Limb / Hand'),

('brown-sequard','IPSI CONTRA',
 'IPSILATERAL: motor loss (CST), proprioception/vibration (DCML). CONTRALATERAL: pain/temperature (ALS), 1–2 levels below lesion',
 'Brown-Séquard syndrome — hemisection of spinal cord: ipsilateral UMN signs + dorsal column loss; contralateral spinothalamic loss.','Spinal Cord');

-- ============================================================
-- QUIZ QUESTIONS
-- ============================================================
INSERT INTO quiz_questions (category, question, options, answer, explanation, difficulty) VALUES

('Cranial Nerves',
 'A 52-year-old with hypertension develops acute onset of ptosis, "down and out" eye position, and diplopia. The pupil is 6mm and non-reactive. Which diagnosis best explains the pupil finding?',
 ARRAY['Medical (ischaemic) CN III palsy (DM/HTN)','Posterior communicating artery aneurysm','Horner syndrome','Cavernous sinus thrombosis'],
 'Posterior communicating artery aneurysm',
 'A dilated, fixed, non-reactive pupil in CN III palsy indicates compression of the outer parasympathetic pupillomotor fibres (which travel on the surface of CN III). This is classic for a PCom aneurysm and is a neurosurgical emergency. In contrast, medical/ischaemic CN III palsy (due to DM or HTN) spares the pupil because ischaemia affects the central fibres first, sparing the peripheral pupillomotor fibres.',
 'hard'),

('Cranial Nerves',
 'A 35-year-old presents with Bell palsy (LMN CN VII). In addition to facial weakness, which finding best localises the lesion to ABOVE the junction of the chorda tympani with the main trunk?',
 ARRAY['Pure motor facial weakness only','Ipsilateral loss of taste on anterior 2/3 tongue','Ipsilateral hyperacusis only','Ipsilateral loss of lacrimation'],
 'Ipsilateral loss of taste on anterior 2/3 tongue',
 'The chorda tympani branches from CN VII in the facial canal and carries taste from the anterior 2/3 tongue + preganglionic parasympathetic fibres to the submandibular/sublingual glands. A lesion above the chorda tympani junction will cause loss of taste (anterior 2/3) in addition to motor palsy. Hyperacusis alone suggests the lesion is above the nerve to stapedius but below the geniculate ganglion. Loss of lacrimation suggests involvement at or above the geniculate ganglion (where the greater petrosal nerve branches).',
 'hard'),

('Brachial Plexus',
 'A neonate is delivered with forceps following shoulder dystocia. Examination reveals the right arm held in adduction with internal rotation at the shoulder and extension at the elbow ("waiter''s tip"). Which nerve roots are primarily injured?',
 ARRAY['C8–T1','C5–C6','C7–C8','C5–T1 (complete plexus avulsion)'],
 'C5–C6',
 'Erb''s palsy results from injury to the upper trunk of the brachial plexus (C5–C6). The mechanism is excessive lateral neck traction during delivery, widening the angle between the head and ipsilateral shoulder. C5–C6 injury causes: deltoid (abduction), supraspinatus (abduction), infraspinatus (ER), biceps (flexion + supination) weakness → arm lies in adduction, internal rotation and elbow extension ("waiter''s tip"). Klumpke''s palsy = C8–T1 injury (claw hand, intrinsic muscles).',
 'medium'),

('Upper Limb',
 'A 40-year-old complains of inability to form a circle with the thumb and index finger, with weakness of thumb IP flexion and index DIP flexion. There is no sensory loss. Which nerve is involved?',
 ARRAY['Ulnar nerve at the elbow','Median nerve at the wrist (carpal tunnel)','Anterior interosseous nerve (AIN)','Radial nerve in the spiral groove'],
 'Anterior interosseous nerve (AIN)',
 'AIN syndrome: pure motor branch of the median nerve that arises in the proximal forearm. It innervates FPL (thumb IP flexion), FDP I and II (index and middle DIP flexion), and pronator quadratus. No sensory loss (AIN is purely motor). The "AIN palsy sign": patient cannot make a complete circle/OK sign — the thumb and index finger form a "pinch" rather than a perfect circle. Causes: Parsonage-Turner syndrome, entrapment by FDS or pronator teres, fractures.',
 'hard'),

('Lower Limb',
 'A 60-year-old post hip replacement patient stands on the left leg and the right pelvis drops. Which muscle is weak and which nerve is affected?',
 ARRAY['Right gluteus maximus — inferior gluteal nerve','Left gluteus medius — superior gluteal nerve','Right tensor fascia lata — superior gluteal nerve','Left piriformis — nerve to piriformis'],
 'Left gluteus medius — superior gluteal nerve',
 'Trendelenburg sign: when standing on the LEFT leg, the pelvis drops on the RIGHT (opposite, unsupported side). This means the left hip abductors (primarily gluteus medius) are WEAK. The gluteus medius is innervated by the superior gluteal nerve (L4–L5). Trendelenburg gait: the patient shifts the trunk to the weak side to compensate. Common causes: superior gluteal nerve injury, hip OA, DDH, after hip replacement.',
 'medium'),

('Spinal Cord',
 'A stabbing victim presents with left-sided weakness below T6, loss of left proprioception and vibration below T6, and loss of right pain and temperature sensation beginning at T8. What is the diagnosis?',
 ARRAY['Complete cord transaction at T6','Anterior cord syndrome','Brown-Séquard syndrome','Central cord syndrome'],
 'Brown-Séquard syndrome',
 'Brown-Séquard syndrome = spinal cord hemisection. Ipsilateral (same side as lesion): UMN motor loss (corticospinal tract) and loss of proprioception/vibration (dorsal column — DCML) below the lesion level. Contralateral: loss of pain and temperature (spinothalamic tract/ALS) beginning 1–2 levels BELOW the lesion (due to decussation in the anterior white commissure). Here the lesion is in the left cord at T6: left motor/dorsal column loss at T6; right pain/temperature loss at T8.',
 'hard'),

('Thorax',
 'During a right-sided chest drain insertion in the 5th intercostal space, through which border of the rib should the trocar pass to avoid the neurovascular bundle?',
 ARRAY['Over the upper border of the 5th rib','Under the lower border of the 4th rib','Through the middle of the intercostal space','Over the upper border of the 6th rib'],
 'Over the upper border of the 6th rib',
 'The intercostal neurovascular bundle (Vein, Artery, Nerve — VAN from superior to inferior) runs in the subcostal groove on the inferior aspect of each rib. To insert a chest drain in the 5th ICS, the trocar must pass OVER THE UPPER BORDER OF THE 6TH RIB to avoid the bundle beneath the 5th rib. This is the most important rule in chest drain insertion. Safe triangle: 4th–5th ICS, anterior to mid-axillary line, lateral to pectoralis major.',
 'medium'),

('Cranial Nerves',
 'A patient with lung cancer develops a hoarse voice. Bronchoscopy reveals a left vocal cord that is fixed in the paramedian position. Which nerve is damaged and what is the anatomical reason for its vulnerability?',
 ARRAY['Left superior laryngeal nerve — damaged at thyroid surgery site','Left recurrent laryngeal nerve — long intrathoracic course under the aortic arch','Right recurrent laryngeal nerve — loops around right subclavian artery','Left hypoglossal nerve — compressed by mediastinal lymph nodes'],
 'Left recurrent laryngeal nerve — long intrathoracic course under the aortic arch',
 'The left recurrent laryngeal nerve (branch of vagus/CN X) has a much longer course than the right: it descends into the mediastinum, loops under the aortic arch, and ascends in the tracheoesophageal groove to the larynx. This long mediastinal course makes it vulnerable to mediastinal pathology (lung cancer, aortic aneurysm, mediastinal lymphadenopathy, cardiac surgery). The RLN innervates all intrinsic laryngeal muscles EXCEPT cricothyroid (external branch of superior laryngeal nerve). Left vocal cord palsy → breathy/hoarse voice.',
 'hard'),

('Anatomy — Abdomen',
 'The duodenojejunal (DJ) flexure is suspended by the ligament of Treitz. Which structure forms this ligament?',
 ARRAY['Peritoneal fold from the right crus of the diaphragm','Suspensory muscle of the duodenum (muscle of Treitz) — fibromuscluar band from right crus of diaphragm','Mesenteric root attachment','Inferior mesenteric vein'],
 'Suspensory muscle of the duodenum (muscle of Treitz) — fibromuscluar band from right crus of diaphragm',
 'The ligament of Treitz is a fibromuscular band (suspensory muscle of the duodenum) that passes from the right crus of the diaphragm to the DJ flexure. It marks the end of the duodenum and beginning of the jejunum — the landmark for the division between upper and lower GI bleeding. Clinically: the DJ flexure lies to the left of the L2 vertebra on AXR; absence or malrotation of this landmark suggests intestinal malrotation.',
 'medium'),

('Peripheral Nerve',
 'A 35-year-old farmer reports severe proximal upper limb pain followed by weakness, with isolated infraspinatus wasting on the right. Shoulder abduction strength is preserved. Which nerve and which specific entrapment site best explains this?',
 ARRAY['Suprascapular nerve at suprascapular notch','Suprascapular nerve at spinoglenoid notch','Axillary nerve at quadrilateral space','Long thoracic nerve at serratus anterior'],
 'Suprascapular nerve at spinoglenoid notch',
 'The suprascapular nerve (C5–C6) supplies supraspinatus (via branch before suprascapular notch) and infraspinatus (via branch after the notch, at the spinoglenoid notch). Entrapment at the SPINOGLENOID NOTCH selectively damages the branch to infraspinatus ONLY — infraspinatus wasting and weakness of external rotation, but supraspinatus (abduction) is preserved. This is seen with spinoglenoid notch cysts (ganglion cysts), volleyball players (repetitive overhead use). Entrapment at the suprascapular notch affects BOTH muscles.',
 'hard'),

('Brainstem / CN',
 'A 65-year-old presents acutely with vertigo, ipsilateral facial pain/temperature loss, contralateral body pain/temperature loss, ipsilateral Horner syndrome, ipsilateral limb ataxia, and dysphagia. Which artery is occluded?',
 ARRAY['Anterior inferior cerebellar artery (AICA)','Basilar artery','Posterior inferior cerebellar artery (PICA) — Wallenberg syndrome','Superior cerebellar artery (SCA)'],
 'Posterior inferior cerebellar artery (PICA) — Wallenberg syndrome',
 'Wallenberg syndrome (lateral medullary syndrome) is caused by PICA or vertebral artery occlusion affecting the lateral medulla. Findings: 1) Ipsilateral face pain/temperature loss (CN V spinal nucleus); 2) Contralateral body pain/temperature loss (spinothalamic tract — already decussated); 3) Ipsilateral Horner syndrome (descending sympathetic fibres); 4) Ipsilateral limb/truncal ataxia (inferior cerebellar peduncle); 5) Dysphagia/dysphonia (nucleus ambiguus, CN IX/X); 6) Nystagmus, vertigo (vestibular nuclei); 7) Ipsilateral palate weakness. Motor power is PRESERVED (pyramidal tracts in medial medulla — AICA territory).',
 'hard'),

('Upper Limb',
 'During anterior shoulder dislocation reduction, a patient develops weakness of deltoid abduction and loss of sensation over the "regimental badge" area. Which nerve is injured and at what location?',
 ARRAY['Musculocutaneous nerve — at coracobrachialis','Axillary nerve — at quadrilateral space / surgical neck of humerus','Radial nerve — in spiral groove','Long thoracic nerve — along medial chest wall'],
 'Axillary nerve — at quadrilateral space / surgical neck of humerus',
 'The axillary nerve (C5–C6, from posterior cord of brachial plexus) passes through the quadrilateral space and winds around the surgical neck of the humerus. It is the most commonly injured nerve in anterior shoulder dislocation and proximal humeral fractures. Axillary nerve palsy: weakness of deltoid (abduction impaired beyond the first 15° — supraspinatus handles initiation), weakness of teres minor, and sensory loss over the "regimental badge" area (upper outer arm). The "quadrilateral space" is bounded by: teres minor, teres major, long head of triceps, and surgical neck of humerus.',
 'medium');
